const SHOP_DATA = [
  {
    title: 'Face',
    items: [
      {
        id: 1,
        name: 'Day Serum',
        imageUrl: 'https://tinyurl.com/4b55j3f2',
        price: 40,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
      {
        id: 2,
        name: 'Night Serum',
        imageUrl: 'https://tinyurl.com/4b55j3f2',
        price: 55,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
      {
        id: 3,
        name: 'Eye Butter',
        imageUrl: 'https://tinyurl.com/4b55j3f2',
        price: 35,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
      {
        id: 4,
        name: 'Anti-Wrinke Serum',
        imageUrl: 'https://tinyurl.com/4b55j3f2',
        price: 50,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
      {
        id: 5,
        name: 'Cleanser',
        imageUrl: 'https://tinyurl.com/4b55j3f2',
        price: 35,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
      {
        id: 6,
        name: 'Gentle Toner',
        imageUrl: 'https://tinyurl.com/4b55j3f2',
        price: 25,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
      {
        id: 7,
        name: 'Problem Skin Toner',
        imageUrl: 'https://tinyurl.com/4b55j3f2',
        price: 25,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
      {
        id: 8,
        name: 'Face Butter',
        imageUrl: 'https://tinyurl.com/4b55j3f2',
        price: 45,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
      {
        id: 9,
        name: 'Lip Balm',
        imageUrl: 'https://tinyurl.com/4b55j3f2',
        price: 15,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
    ],
  },
  {
    title: 'Body',
    items: [
      {
        id: 10,
        name: 'Body Oil',
        imageUrl: 'https://tinyurl.com/2mjf6h8j',
        price: 50,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
      {
        id: 11,
        name: 'Face & Body Mask',
        imageUrl: 'https://tinyurl.com/2mjf6h8j',
        price: 35,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
      {
        id: 12,
        name: 'Moringa Body Butter',
        imageUrl: 'https://tinyurl.com/2mjf6h8j',
        price: 45,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
      {
        id: 13,
        name: 'Body Butter',
        imageUrl: 'https://tinyurl.com/2mjf6h8j',
        price: 45,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
      {
        id: 14,
        name: 'Solid Body Butter No1',
        imageUrl: 'https://tinyurl.com/2mjf6h8j',
        price: 35,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
      {
        id: 15,
        name: 'Solid Body Butter No2',
        imageUrl: 'https://tinyurl.com/2mjf6h8j',
        price: 35,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
      {
        id: 16,
        name: 'Body Scrub',
        imageUrl: 'https://tinyurl.com/2mjf6h8j',
        price: 30,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
      {
        id: 17,
        name: 'Deodorant',
        imageUrl: 'https://tinyurl.com/2mjf6h8j',
        price: 25,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
    ],
  },
  {
    title: 'Cleanse',
    items: [
      {
        id: 18,
        name: 'Toothpaste',
        imageUrl: 'https://tinyurl.com/2mjf6h8j',
        price: 15,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
      {
        id: 19,
        name: 'Mouthwash',
        imageUrl: 'https://tinyurl.com/2mjf6h8j',
        price: 20,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
      {
        id: 20,
        name: 'Natural Cleanse Bar',
        imageUrl: 'https://tinyurl.com/2mjf6h8j',
        price: 15,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
    ],
  },
  {
    title: 'Hair',
    items: [
      {
        id: 21,
        name: 'Shampoo Liquid',
        imageUrl: 'https://tinyurl.com/vznp2rs4',
        price: 25,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
      {
        id: 22,
        name: 'Shampoo Powder',
        imageUrl: 'https://tinyurl.com/vznp2rs4',
        price: 20,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
      {
        id: 23,
        name: 'Conditioner',
        imageUrl: 'https://tinyurl.com/vznp2rs4',
        price: 25,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
      {
        id: 24,
        name: 'Hair Mask',
        imageUrl: 'https://tinyurl.com/vznp2rs4',
        price: 25,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
    ],
  },
  {
    title: 'Hands',
    items: [
      {
        id: 25,
        name: 'Hand Butter',
        imageUrl: 'https://tinyurl.com/4b55j3f2',
        price: 25,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
    ],
  },
  {
    title: 'Massage',
    items: [
      {
        id: 26,
        name: 'Mood Enhancing Oil',
        imageUrl: 'https://tinyurl.com/ywzrcyff',
        price: 45,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
      {
        id: 27,
        name: 'Massage Oil',
        imageUrl: 'https://tinyurl.com/ywzrcyff',
        price: 45,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
      {
        id: 28,
        name: 'Stress Oil',
        imageUrl: 'https://tinyurl.com/ywzrcyff',
        price: 45,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
      {
        id: 29,
        name: 'Inflammation/Sore Muscle Oil',
        imageUrl: 'https://tinyurl.com/ywzrcyff',
        price: 25,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
    ],
  },
  {
    title: 'Scents',
    items: [
      {
        id: 30,
        name: 'Fragrant Body Mist',
        imageUrl: 'https://tinyurl.com/vznp2rs4',
        price: 35,
        description: 'fjldsfds',
        ingredients: 'weroewr',
        instructions: 'hytthythy',
      },
    ],
  },
];

export default SHOP_DATA;